## Resumen del DataFrame Chicago.csv

In [4]:
import pandas as pd

In [25]:
data = pd.read_csv('../Pandas/chicago.csv')

In [ ]:
data.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [11]:
data.shape

(32063, 4)

In [13]:
data.describe()

                      Name  Position Title Department Employee Annual Salary
count                32062           32062      32062                  32062
unique               31776            1093         35                   1156
top     HERNANDEZ,  JUAN C  POLICE OFFICER     POLICE              $87384.00
freq                     4            9184      12618                   2394

In [ ]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 32063 entries, 0 to 32062
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  str
 1   Position Title          32062 non-null  str
 2   Department              32062 non-null  str
 3   Employee Annual Salary  32062 non-null  str
dtypes: str(4)
memory usage: 1002.1 KB

In [ ]:
# Elimina símbolos y convierte a numérico
data['Employee Annual Salary'] = data['Employee Annual Salary'].replace('[\$,]', '', regex=True).astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
C:\Users\santi\AppData\Local\Temp\ipykernel_8356\128734523.py:2: SyntaxWarning: invalid escape sequence '\$'
  data['Employee Annual Salary'] = data['Employee Annual Salary'].replace('[\$,]', '', regex=True).astype(float)

Media: 80204.17863389681, Mediana: 84450.0, Moda: 87384.0

In [30]:
media = data['Employee Annual Salary'].mean()
mediana = data['Employee Annual Salary'].median()
moda = data['Employee Annual Salary'].mode()[0]

print(f'Media: {media}, Mediana: {mediana}, Moda: {moda}')

Media: 80204.17863389681, Mediana: 84450.0, Moda: 87384.0

In [20]:
resumen = data.describe()
print(resumen)

                      Name  Position Title Department Employee Annual Salary
count                32062           32062      32062                  32062
unique               31776            1093         35                   1156
top     HERNANDEZ,  JUAN C  POLICE OFFICER     POLICE              $87384.00
freq                     4            9184      12618                   2394

In [31]:
Varianza = data['Employee Annual Salary'].var()
Desviacion_Estandar = data['Employee Annual Salary'].std()
print(f'Varianza: {Varianza}, Desviación Estándar: {Desviacion_Estandar}')

Varianza: 629926162.1383415, Desviación Estándar: 25098.32986750994

In [32]:
Rango = data['Employee Annual Salary'].max() - data['Employee Annual Salary'].min()
print(f'Rango: {Rango}')

Rango: 299999.04