## Datasets ##

In [3]:
import pandas as pd

In [4]:
! pip install pandas # Para instalar pandas

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Invalid requirement: '#': Expected package name at the start of dependency specifier
    #
    ^

In [5]:
nba = pd.read_csv("nba.csv") # Se carga com los marcos de cuadro de trabajo
nba.head() # Muestra las primeras filas

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [6]:
nba.tail() # Muestra las ultimas filas y columnas

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
nba.index # Muestra el indice del DataFrame

RangeIndex(start=0, stop=458, step=1)

In [8]:
nba.values # Muestra los valores de todo el DataFrame

array([['Avery Bradley', 'Boston Celtics', 0.0, ..., 180.0, 'Texas',
        7730337.0],
       ['Jae Crowder', 'Boston Celtics', 99.0, ..., 235.0, 'Marquette',
        6796117.0],
       ['John Holland', 'Boston Celtics', 30.0, ..., 205.0,
        'Boston University', nan],
       ...,
       ['Tibor Pleiss', 'Utah Jazz', 21.0, ..., 256.0, nan, 2900000.0],
       ['Jeff Withey', 'Utah Jazz', 24.0, ..., 231.0, 'Kansas', 947276.0],
       [nan, nan, nan, ..., nan, nan, nan]], shape=(458, 9), dtype=object)

In [9]:
nba.shape # Muestra filas y columnas

(458, 9)

In [10]:
nba.dtypes # Muestra el tipode dato de cada columna

Name            str
Team            str
Number      float64
Position        str
Age         float64
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

In [11]:
nba.head(1) # Muestra el primer elemento del dataFrame

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0

In [12]:
lista_cols = nba.columns

In [13]:
for i in lista_cols:
    print(i)

Name
Team
Number
Position
Age
Height
Weight
College
Salary

In [14]:
nba.info() # Muestra la información acerca del DataFrame, como filas y columnas, tipos de datos, memoria, etc.

<class 'pandas.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    str
 1   Team      457 non-null    str
 2   Number    457 non-null    float64
 3   Position  457 non-null    str
 4   Age       457 non-null    float64
 5   Height    457 non-null    str
 6   Weight    457 non-null    float64
 7   College   373 non-null    str
 8   Salary    446 non-null    float64
dtypes: float64(4), str(5)
memory usage: 32.3 KB

In [15]:
pd.read_csv("revenue.csv")

      Date  New York  Los Angeles  Miami
0   1/1/16       985          122    499
1   1/2/16       738          788    534
2   1/3/16        14           20    933
3   1/4/16       730          904    885
4   1/5/16       114           71    253
5   1/6/16       936          502    497
6   1/7/16       123          996    115
7   1/8/16       935          492    886
8   1/9/16       846          954    823
9  1/10/16        54          285    216

In [16]:
pd.read_csv("revenue.csv", index_col = "Date")

         New York  Los Angeles  Miami
Date
1/1/16        985          122    499
1/2/16        738          788    534
1/3/16         14           20    933
1/4/16        730          904    885
1/5/16        114           71    253
1/6/16        936          502    497
1/7/16        123          996    115
1/8/16        935          492    886
1/9/16        846          954    823
1/10/16        54          285    216

In [17]:
rev = pd.read_csv("revenue.csv", index_col = "Date")

In [18]:
rev.head(5)

        New York  Los Angeles  Miami
Date
1/1/16       985          122    499
1/2/16       738          788    534
1/3/16        14           20    933
1/4/16       730          904    885
1/5/16       114           71    253

In [19]:
rev.sum()

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [20]:
nba = pd.read_csv("nba.csv")

In [21]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [22]:
nba.Name # Muestra solo la columna de Name

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: str

In [23]:
nba.Age

0      25.0
1      25.0
2      27.0
3      22.0
4      29.0
       ...
453    26.0
454    24.0
455    26.0
456    26.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [24]:
prom_edades = nba.Age.mean()

In [25]:
prom_edades

np.float64(26.938730853391686)

In [26]:
nba.Position.tail(10) # Muestra los ultimos 10 elementos de la columna posiciones

448     SF
449     SG
450     SF
451     SF
452     PF
453     PG
454     PG
455      C
456      C
457    NaN
Name: Position, dtype: str

In [27]:
nba.Height.tail(4) # Muestra los ultimos 4 elementos de la columna Height

454    6-1
455    7-3
456    7-0
457    NaN
Name: Height, dtype: str

In [28]:
nba["Name"]

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: str

In [29]:
nba["Name"].head()

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
Name: Name, dtype: str

In [30]:
nba[["Team", "Name", "Age"]].head()

             Team           Name   Age
0  Boston Celtics  Avery Bradley  25.0
1  Boston Celtics    Jae Crowder  25.0
2  Boston Celtics   John Holland  27.0
3  Boston Celtics    R.J. Hunter  22.0
4  Boston Celtics  Jonas Jerebko  29.0

In [31]:
nba[["Number", "College"]].tail()

     Number College
453     8.0  Butler
454    25.0     NaN
455    21.0     NaN
456    24.0  Kansas
457     NaN     NaN

In [32]:
select = ["Salary", "Team", "Name"]

In [33]:
nba[select]

        Salary            Team           Name
0    7730337.0  Boston Celtics  Avery Bradley
1    6796117.0  Boston Celtics    Jae Crowder
2          NaN  Boston Celtics   John Holland
3    1148640.0  Boston Celtics    R.J. Hunter
4    5000000.0  Boston Celtics  Jonas Jerebko
..         ...             ...            ...
453  2433333.0       Utah Jazz   Shelvin Mack
454   900000.0       Utah Jazz      Raul Neto
455  2900000.0       Utah Jazz   Tibor Pleiss
456   947276.0       Utah Jazz    Jeff Withey
457        NaN             NaN            NaN

[458 rows x 3 columns]

In [34]:
for l in select:
    print(l)

Salary
Team
Name

In [35]:
nba["Sport"] = "Basketball"

In [36]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball

In [37]:
nba["League"] = "National Basketball Association"

In [38]:
nba.head(2)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport,League
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball,National Basketball Association
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball,National Basketball Association

In [39]:
nba = pd.read_csv("nba.csv")

In [40]:
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
nba.insert(3, column = "Sport", value = "Basketball")

In [42]:
nba.head(4)

,Name,Team,Number,Sport,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,Basketball,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,Basketball,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,Basketball,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,Basketball,SG,22.0,6-5,185.0,Georgia State,1148640.0

## Broadcasting Operations ##

In [43]:
nba = pd.read_csv("nba.csv")

In [44]:
nba["Age"].head(3)

0    25.0
1    25.0
2    27.0
Name: Age, dtype: float64

In [45]:
nba["Age"].add(5)

0      30.0
1      30.0
2      32.0
3      27.0
4      34.0
       ...
453    31.0
454    29.0
455    31.0
456    31.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [46]:
nba["Age"]+5
nba.head(2)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0

In [47]:
nba["Salary"]

0      7730337.0
1      6796117.0
2            NaN
3      1148640.0
4      5000000.0
         ...
453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
457          NaN
Name: Salary, Length: 458, dtype: float64

In [48]:
nba["Team"].value_counts()

Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Philadelphia 76ers        15
Toronto Raptors           15
Golden State Warriors     15
Los Angeles Clippers      15
Los Angeles Lakers        15
Phoenix Suns              15
Sacramento Kings          15
Chicago Bulls             15
Cleveland Cavaliers       15
Detroit Pistons           15
Indiana Pacers            15
Dallas Mavericks          15
Houston Rockets           15
San Antonio Spurs         15
Atlanta Hawks             15
Charlotte Hornets         15
Miami Heat                15
Washington Wizards        15
Denver Nuggets            15
Oklahoma City Thunder     15
Portland Trail Blazers    15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64

In [49]:
nba["Position"].value_counts().head(5)

Position
SG    102
PF    100
PG     92
SF     85
C      78
Name: count, dtype: int64

In [50]:
peso = nba["Weight"].value_counts().head(4)

In [51]:
nba["Salary"].value_counts().tail(4)

Salary
2050000.0    1
2239800.0    1
2433333.0    1
900000.0     1
Name: count, dtype: int64

## Drop rows eith Null Values ##

In [52]:
nba = pd.read_csv("nba.csv")

In [53]:
nba.tail(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
nba.dropna # Borra todos los valores null

<bound method DataFrame.dropna of               Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0
457                NaN        NaN

[458 rows x 9 columns]>

In [55]:
nba.dropna(how = "all") # Borra solo las filas que tienen todos los valores null

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [56]:
nba.dropna(how = "all", inplace = True) # Borra las filas que tienen todos los valores null y lo guarda en el mismo DataFrame

In [57]:
nba.dropna(axis = 1) # Borra las columnas que tienen al menos un valor null, axis = 1 se refiere a columnas, axis = 0 se refiere a filas

              Name            Team  Number Position   Age Height  Weight
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0

[457 rows x 7 columns]

In [58]:
nba.dropna(subset = ["Salary"]) # Borra las filas que tienen valores null en la columna Salary

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

## Fill in Null Values with the .fillna() Method ##

In [59]:
nba.fillna(0) # Rellena los valores null con 0

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,0,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,0,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,0,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [60]:
nba = pd.read_csv("nba.csv")

In [61]:
nba["Salary"] = nba["Salary"].fillna(0, inplace = True)

C:\Users\santi\AppData\Local\Temp\ipykernel_10056\1660811082.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  nba["Salary"] = nba["Salary"].fillna(0, inplace = True)

In [62]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [63]:
nba["College"] = nba["College"].fillna("No College")

In [64]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,No College,5000000.0

In [65]:
nba["College"].fillna("None", inplace = True)

C:\Users\santi\AppData\Local\Temp\ipykernel_10056\3218354694.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  nba["College"].fillna("None", inplace = True)

0                  Texas
1              Marquette
2      Boston University
3          Georgia State
4             No College
             ...
453               Butler
454           No College
455           No College
456               Kansas
457           No College
Name: College, Length: 458, dtype: str

In [66]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,No College,5000000.0

In [67]:
nba.dtypes

Name            str
Team            str
Number      float64
Position        str
Age         float64
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

In [68]:
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    str
 1   Team      457 non-null    str
 2   Number    457 non-null    float64
 3   Position  457 non-null    str
 4   Age       457 non-null    float64
 5   Height    457 non-null    str
 6   Weight    457 non-null    float64
 7   College   458 non-null    str
 8   Salary    458 non-null    float64
dtypes: float64(4), str(5)
memory usage: 32.3 KB

In [69]:
nba["Salary"].astype("int")

0      7730337
1      6796117
2            0
3      1148640
4      5000000
        ...
453    2433333
454     900000
455    2900000
456     947276
457          0
Name: Salary, Length: 458, dtype: int64

In [70]:
nba["Age"].astype("float")

0      25.0
1      25.0
2      27.0
3      22.0
4      29.0
       ...
453    26.0
454    24.0
455    26.0
456    26.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [71]:
nba["Number"].astype("float")

0       0.0
1      99.0
2      30.0
3      28.0
4       8.0
       ...
453     8.0
454    25.0
455    21.0
456    24.0
457     NaN
Name: Number, Length: 458, dtype: float64

In [72]:
nba["Weight"].astype("float")

0      180.0
1      235.0
2      205.0
3      185.0
4      231.0
       ...
453    203.0
454    179.0
455    256.0
456    231.0
457      NaN
Name: Weight, Length: 458, dtype: float64

In [73]:
nba["Position"].nunique() # Regresa el numero de valores unicos en la columna Position

5

In [74]:
nba.sort_values("Name", ascending = True)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
328,Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
404,Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,1938840.0
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
...,...,...,...,...,...,...,...,...,...
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,0.0
402,Zach LaVine,Minnesota Timberwolves,8.0,PG,21.0,6-5,189.0,UCLA,2148360.0
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,No College,5200000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No College,0.0

In [75]:
nba.sort_values("Salary", ascending = False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,No College,25000000.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,No College,22970500.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,No College,22359364.0
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
...,...,...,...,...,...,...,...,...,...
353,Dorell Wright,Miami Heat,11.0,SF,30.0,6-9,205.0,No College,0.0
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,0.0
397,Axel Toupane,Denver Nuggets,6.0,SG,23.0,6-7,210.0,No College,0.0
409,Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6-10,250.0,Fresno State,0.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No College,0.0

In [76]:
# Ingresar un jugador por teclado y localizarlo en el dataFrame con nombre y apellido

import pandas as pd

# 1. Cargar el archivo CSV
df = pd.read_csv('nba.csv')

# 2. Solicitar el nombre por teclado
nombre_buscado = input("Ingresa el nombre y apellido del jugador: ")

# 3. Localizar al jugador
# Usamos .str.lower() en ambos lados para que la búsqueda sea más flexible
resultado = df[df['Name'].str.lower() == nombre_buscado.lower()]

# 4. Mostrar el resultado
if not resultado.empty:
    print("\n--- Jugador Localizado ---")
    print(resultado)
else:
    print(f"\nNo se encontró a '{nombre_buscado}' en el archivo nba.csv.")

No se encontró a '' en el archivo nba.csv.

In [77]:
import pandas as pd 
nba = pd.read_csv("nba.csv")

In [78]:
nba.sort_values("Age", ascending = False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
400,Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,NaN,8500000.0
298,Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,5250000.0
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,250750.0
261,Vince Carter,Memphis Grizzlies,15.0,SG,39.0,6-6,220.0,North Carolina,4088019.0
102,Pablo Prigioni,Los Angeles Clippers,9.0,PG,39.0,6-3,185.0,NaN,947726.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
410,Karl-Anthony Towns,Minnesota Timberwolves,32.0,C,20.0,7-0,244.0,Kentucky,5703600.0
226,Rashad Vaughn,Milwaukee Bucks,20.0,SG,19.0,6-6,202.0,UNLV,1733040.0
122,Devin Booker,Phoenix Suns,1.0,SG,19.0,6-6,206.0,Kentucky,2127840.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [80]:
nba.sort_values(["Team", "Name"], ascending = True)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
318,Dennis Schroder,Atlanta Hawks,17.0,PG,22.0,6-1,172.0,NaN,1763400.0
323,Jeff Teague,Atlanta Hawks,0.0,PG,27.0,6-2,186.0,Wake Forest,8000000.0
309,Kent Bazemore,Atlanta Hawks,24.0,SF,26.0,6-5,201.0,Old Dominion,2000000.0
311,Kirk Hinrich,Atlanta Hawks,12.0,SG,35.0,6-4,190.0,Kansas,2854940.0
...,...,...,...,...,...,...,...,...,...
376,Markieff Morris,Washington Wizards,5.0,PF,26.0,6-10,245.0,Kansas,8000000.0
375,Nene Hilario,Washington Wizards,42.0,C,33.0,6-11,250.0,NaN,13000000.0
378,Otto Porter Jr.,Washington Wizards,22.0,SF,23.0,6-8,198.0,Georgetown,4662960.0
379,Ramon Sessions,Washington Wizards,7.0,PG,30.0,6-3,190.0,Nevada,2170465.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
nba.sort_values(["Team", "Name"], ascending = [False, True])

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
368,Alan Anderson,Washington Wizards,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0
369,Bradley Beal,Washington Wizards,3.0,SG,22.0,6-5,207.0,Florida,5694674.0
372,Drew Gooden,Washington Wizards,90.0,PF,34.0,6-10,250.0,Kansas,3300000.0
380,Garrett Temple,Washington Wizards,17.0,SG,30.0,6-6,195.0,LSU,1100602.0
374,JJ Hickson,Washington Wizards,21.0,C,27.0,6-9,242.0,North Carolina State,273038.0
...,...,...,...,...,...,...,...,...,...
320,Thabo Sefolosha,Atlanta Hawks,25.0,SF,32.0,6-7,220.0,NaN,4000000.0
321,Tiago Splitter,Atlanta Hawks,11.0,C,31.0,6-11,245.0,NaN,9756250.0
310,Tim Hardaway Jr.,Atlanta Hawks,10.0,SG,24.0,6-6,205.0,Michigan,1304520.0
322,Walter Tavares,Atlanta Hawks,22.0,C,24.0,7-3,260.0,NaN,1000000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Sort DataFrame ##

In [82]:
nba = pd.read_csv("nba.csv")

In [83]:
nba.sort_values(["Number", "Salary", "Name"])

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
291,Orlando Johnson,New Orleans Pelicans,0.0,SG,27.0,6-5,220.0,UC Santa Barbara,55722.0
248,Andrew Goudelock,Houston Rockets,0.0,PG,27.0,6-3,200.0,Charleston,200600.0
347,Josh Richardson,Miami Heat,0.0,SG,22.0,6-6,200.0,Tennessee,525093.0
266,JaMychal Green,Memphis Grizzlies,0.0,PF,25.0,6-9,227.0,Alabama,845059.0
47,Isaiah Canaan,Philadelphia 76ers,0.0,PG,25.0,6-0,201.0,Murray State,947276.0
...,...,...,...,...,...,...,...,...,...
372,Drew Gooden,Washington Wizards,90.0,PF,34.0,6-10,250.0,Kansas,3300000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
68,Lucas Nogueira,Toronto Raptors,92.0,C,23.0,7-0,220.0,NaN,1842000.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
nba.sort_index

<bound method DataFrame.sort_index of               Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0
457                NaN        NaN

[458 rows x 9 columns]>

In [85]:
nba.sort_index(ascending = False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
...,...,...,...,...,...,...,...,...,...
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0

## The set_index and reset_index

In [86]:
b = pd.read_csv("jamesbond.csv")
b.tail()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [87]:
b = pd.read_csv("jamesbond.csv", index_col = "Film")
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [88]:
bb = pd.read_csv("jamesbond.csv")
bb.head(3)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [89]:
bb.set_index(keys="Film") # Sirve para declarar una columna como un indice

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [90]:
bb.reset_index() # Reinica el index y regresa el que esta por default de la libreria de pandas

,index,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [91]:
bb.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [92]:
bb.reset_index(drop = True)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [93]:
bb.set_index("Film", inplace = True)

In [94]:
bb.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [95]:
bb.set_index("Year")

,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,
1962,Sean Connery,Terence Young,448.8,7.0,0.6
1963,Sean Connery,Terence Young,543.8,12.6,1.6
1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,Sean Connery,Terence Young,848.1,41.9,4.7
1967,David Niven,Ken Hughes,315.0,85.0,NaN
1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
1981,Roger Moore,John Glen,449.4,60.2,NaN
1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
1983,Roger Moore,John Glen,373.8,53.9,7.8
1985,Roger Moore,John Glen,275.2,54.5,9.1
1987,Timothy Dalton,John Glen,313.5,68.8,5.2
1989,Timothy Dalton,John Glen,250.9,56.7,7.9
1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [96]:
bb.reset_index(inplace = True)

In [97]:
bb.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

# Retrieve rows by index Label with .loc() Acessor

In [98]:
import pandas as pd
b = pd.read_csv("jamesbond.csv", index_col="Film")
b.sort_index(inplace = True, ascending = True)
b.head(13)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN

In [99]:
b.loc["Goldfinger"]

Year                         1964
Actor                Sean Connery
Director             Guy Hamilton
Box Office                  820.4
Budget                       18.6
Bond Actor Salary             3.2
Name: Goldfinger, dtype: object

In [100]:
b.loc["GoldenEye"]

Year                            1995
Actor                 Pierce Brosnan
Director             Martin Campbell
Box Office                     518.5
Budget                          76.9
Bond Actor Salary                5.1
Name: GoldenEye, dtype: object

In [101]:
b.loc["Casino Royale"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [102]:
b.loc["Diamonds Are Forever": "From Rusia with Love"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN

In [103]:
b.loc["Diamonds Are Forever": "From Rusia with Love":2] # Se salta de 2 en 2

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6

In [104]:
b.loc["GoldenEye":].head(5)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN

In [105]:
b.loc[:"On Her Majestary´s Secret Service"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8

In [106]:
b.loc[["Die Another Day", "Octopussy"]]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8

## Retrieve rows by index Position iloc Accessor

In [107]:
b = pd.read_csv("jamesbond.csv")
b.head(3)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [108]:
b.iloc[0] # Manda pedir lo que se tiene en la posicion 0 usando el método iloc

Film                        Dr. No
Year                          1962
Actor                 Sean Connery
Director             Terence Young
Box Office                   448.8
Budget                         7.0
Bond Actor Salary              0.6
Name: 0, dtype: object

In [109]:
b.iloc[[10,20]]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5

In [110]:
b.iloc[4:8]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8

In [111]:
b.iloc[20:]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [112]:
b.iloc[:8]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8

In [113]:
b.iloc[[5,4,2]]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

## Accesors

In [114]:
import pandas as pd
b = pd.read_csv("jamesbond.csv", index_col = "Film")
b.sort_index(inplace = True)
b.head(13)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN

In [115]:
b.loc["Moonraker","Actor"] # Indica el nombre de dicha pelicula

'Roger Moore'

In [116]:
b.loc["Moonraker", "Director"] # Indica el nombre del director de la pelicula

'Lewis Gilbert'

In [117]:
b.loc["Moonraker", ["Director", "Box Office"]]

Director      Lewis Gilbert
Box Office            535.0
Name: Moonraker, dtype: object

In [118]:
b.loc["Moonraker": "Thunderball" , "Director": "Budget"]

                                       Director  Box Office  Budget
Film
Moonraker                         Lewis Gilbert       535.0    91.5
Never Say Never Again            Irvin Kershner       380.0    86.0
Octopussy                             John Glen       373.8    53.9
On Her Majesty's Secret Service   Peter R. Hunt       291.5    37.3
Quantum of Solace                  Marc Forster       514.2   181.4
Skyfall                              Sam Mendes       943.5   170.2
Spectre                              Sam Mendes       726.7   206.3
The Living Daylights                  John Glen       313.5    68.8
The Man with the Golden Gun        Guy Hamilton       334.0    27.7
The Spy Who Loved Me              Lewis Gilbert       533.0    45.1
The World Is Not Enough           Michael Apted       439.5   158.3
Thunderball                       Terence Young       848.1    41.9

In [119]:
b.loc["Moonraker":, "Director": "Budget"]

                                           Director  Box Office  Budget
Film
Moonraker                             Lewis Gilbert       535.0    91.5
Never Say Never Again                Irvin Kershner       380.0    86.0
Octopussy                                 John Glen       373.8    53.9
On Her Majesty's Secret Service       Peter R. Hunt       291.5    37.3
Quantum of Solace                      Marc Forster       514.2   181.4
Skyfall                                  Sam Mendes       943.5   170.2
Spectre                                  Sam Mendes       726.7   206.3
The Living Daylights                      John Glen       313.5    68.8
The Man with the Golden Gun            Guy Hamilton       334.0    27.7
The Spy Who Loved Me                  Lewis Gilbert       533.0    45.1
The World Is Not Enough               Michael Apted       439.5   158.3
Thunderball                           Terence Young       848.1    41.9
Tomorrow Never Dies              Roger Spottiswoode       463.2   133.9
You Only Live Twice                   Lewis Gilbert       514.2    59.9

In [120]:
b.iloc[14,2]

'John Glen'

In [121]:
b.iloc[14, 2:5]

Director      John Glen
Box Office        373.8
Budget             53.9
Name: Octopussy, dtype: object

In [122]:
b.iloc[[14, 17], 2:5] # Me regresa solo la filas 14 y 17, y las columnas desde la 2 a la 4 porque la 5 no la muestra

             Director  Box Office  Budget
Film
Octopussy   John Glen       373.8    53.9
Skyfall    Sam Mendes       943.5   170.2

In [123]:
b.iloc[:7, :3]

                      Year           Actor         Director
Film
A View to a Kill      1985     Roger Moore        John Glen
Casino Royale         2006    Daniel Craig  Martin Campbell
Casino Royale         1967     David Niven       Ken Hughes
Diamonds Are Forever  1971    Sean Connery     Guy Hamilton
Die Another Day       2002  Pierce Brosnan     Lee Tamahori
Dr. No                1962    Sean Connery    Terence Young
For Your Eyes Only    1981     Roger Moore        John Glen

# Colocar nuevo valor a una celda especifica

In [124]:
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [125]:
b.loc["Dr. No", "Actor"]

'Sean Connery'

In [126]:
b.loc["Dr. No", "Actor"] = "Sir Sean Connery"

In [127]:
b.loc["Dr. No", "Actor"]

'Sir Sean Connery'

In [128]:
b.loc["Dr. No", ["Box Office", "Budget", "Bond Actor Salary"]] = [448000, 700000, 60000]

In [129]:
b.loc["Dr. No", ["Box Office", "Budget", "Bond Actor Salary"]].head(3)

Box Office           448000.0
Budget               700000.0
Bond Actor Salary     60000.0
Name: Dr. No, dtype: float64

In [130]:
b.loc["Dr. No"]

Year                             1962
Actor                Sir Sean Connery
Director                Terence Young
Box Office                   448000.0
Budget                       700000.0
Bond Actor Salary             60000.0
Name: Dr. No, dtype: object

# Colocar multiples valores en un DataFrame

In [131]:
import pandas as pd
b = pd.read_csv("jamesbond.csv", index_col = "Film")
b.sort_index(inplace = True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [132]:
b["Actor"] == "Sean Connery"

Film
A View to a Kill                   False
Casino Royale                      False
Casino Royale                      False
Diamonds Are Forever                True
Die Another Day                    False
Dr. No                              True
For Your Eyes Only                 False
From Russia with Love               True
GoldenEye                          False
Goldfinger                          True
Licence to Kill                    False
Live and Let Die                   False
Moonraker                          False
Never Say Never Again               True
Octopussy                          False
On Her Majesty's Secret Service    False
Quantum of Solace                  False
Skyfall                            False
Spectre                            False
The Living Daylights               False
The Man with the Golden Gun        False
The Spy Who Loved Me               False
The World Is Not Enough            False
Thunderball                         True
Tomorrow Never Dies                False
You Only Live Twice                 True
Name: Actor, dtype: bool

In [133]:
actor_is_sean_connery = b["Actor"] == "Sean Connery" # Crea una seria donde indica si el actor si es o no

In [134]:
print(actor_is_sean_connery)

Film
A View to a Kill                   False
Casino Royale                      False
Casino Royale                      False
Diamonds Are Forever                True
Die Another Day                    False
Dr. No                              True
For Your Eyes Only                 False
From Russia with Love               True
GoldenEye                          False
Goldfinger                          True
Licence to Kill                    False
Live and Let Die                   False
Moonraker                          False
Never Say Never Again               True
Octopussy                          False
On Her Majesty's Secret Service    False
Quantum of Solace                  False
Skyfall                            False
Spectre                            False
The Living Daylights               False
The Man with the Golden Gun        False
The Spy Who Loved Me               False
The World Is Not Enough            False
Thunderball                         True
Tomorrow Never Dies                False
You Only Live Twice                 True
Name: Actor, dtype: bool

In [135]:
b[actor_is_sean_connery]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [136]:
b.loc[actor_is_sean_connery, "Actor"] = "Sir Sean Connery" # Cambia el nombre del actor donde sea Sean Connery por Sir Sean Connery

In [137]:
b.loc[actor_is_sean_connery]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

# Renombrar etiquetas del index

In [138]:
import pandas as pd
b = pd.read_csv("jamesbond.csv", index_col = "Film")
b.sort_index(inplace = True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [139]:
b.rename(mapper = {"GoldenEye": "Golden Eye", "The World Is Not Enough": "The World Is Your"})

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Your,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [140]:
b.rename(index = {"GoldenEye": "Golden Eye", "The World Is Not Enough": "The World Is Your"})

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Your,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [141]:
# Muestra solo la fila de la pelicula Golden Eye
b.loc["GoldenEye","Year": "Budget"]

Year                     1995
Actor          Pierce Brosnan
Director      Martin Campbell
Box Office              518.5
Budget                   76.9
Name: GoldenEye, dtype: object

In [142]:
b.rename(mapper = {"Year": "Release Date", "Box Office": "Revenue"},axis = 1) # Cambiar el nombre de las columnas

,Release Date,Actor,Director,Revenue,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [143]:
b.columns

Index(['Year', 'Actor', 'Director', 'Box Office', 'Budget',
       'Bond Actor Salary'],
      dtype='str')

In [144]:
b.columns = ["Year of Release", "Actor", "Director", "Gross", "Cost", "Salary"] # Cambiar el nombre a las columnas

In [145]:
b.columns

Index(['Year of Release', 'Actor', 'Director', 'Gross', 'Cost', 'Salary'], dtype='str')

In [146]:
import pandas as pd
b = pd.read_csv("jamesbond.csv", index_col = "Film")
b.sort_index(inplace = True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [147]:
b.drop("A View to a Kill")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [148]:
b.drop(["A View to a Kill", "Casino Royale"])

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [149]:
b.drop("Box Office", axis = 1) # axis = 1 representas las columnas

,Year,Actor,Director,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,1985,Roger Moore,John Glen,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,59.9,4.4

In [150]:
b.drop(["Box Office", "Actor"], axis = 1)

,Year,Director,Budget,Bond Actor Salary
Film,,,,
A View to a Kill,1985,John Glen,54.5,9.1
Casino Royale,2006,Martin Campbell,145.3,3.3
Casino Royale,1967,Ken Hughes,85.0,NaN
Diamonds Are Forever,1971,Guy Hamilton,34.7,5.8
Die Another Day,2002,Lee Tamahori,154.2,17.9
Dr. No,1962,Terence Young,7.0,0.6
For Your Eyes Only,1981,John Glen,60.2,NaN
From Russia with Love,1963,Terence Young,12.6,1.6
GoldenEye,1995,Martin Campbell,76.9,5.1
Goldfinger,1964,Guy Hamilton,18.6,3.2
Licence to Kill,1989,John Glen,56.7,7.9
Live and Let Die,1973,Guy Hamilton,30.8,NaN
Moonraker,1979,Lewis Gilbert,91.5,NaN
Never Say Never Again,1983,Irvin Kershner,86.0,NaN
Octopussy,1983,John Glen,53.9,7.8
On Her Majesty's Secret Service,1969,Peter R. Hunt,37.3,0.6
Quantum of Solace,2008,Marc Forster,181.4,8.1
Skyfall,2012,Sam Mendes,170.2,14.5
Spectre,2015,Sam Mendes,206.3,NaN
The Living Daylights,1987,John Glen,68.8,5.2
The Man with the Golden Gun,1974,Guy Hamilton,27.7,NaN
The Spy Who Loved Me,1977,Lewis Gilbert,45.1,NaN
The World Is Not Enough,1999,Michael Apted,158.3,13.5
Thunderball,1965,Terence Young,41.9,4.7
Tomorrow Never Dies,1997,Roger Spottiswoode,133.9,10.0
You Only Live Twice,1967,Lewis Gilbert,59.9,4.4

In [151]:
actor = b.pop("Actor")

In [152]:
actor

Film
A View to a Kill                      Roger Moore
Casino Royale                        Daniel Craig
Casino Royale                         David Niven
Diamonds Are Forever                 Sean Connery
Die Another Day                    Pierce Brosnan
Dr. No                               Sean Connery
For Your Eyes Only                    Roger Moore
From Russia with Love                Sean Connery
GoldenEye                          Pierce Brosnan
Goldfinger                           Sean Connery
Licence to Kill                    Timothy Dalton
Live and Let Die                      Roger Moore
Moonraker                             Roger Moore
Never Say Never Again                Sean Connery
Octopussy                             Roger Moore
On Her Majesty's Secret Service    George Lazenby
Quantum of Solace                    Daniel Craig
Skyfall                              Daniel Craig
Spectre                              Daniel Craig
The Living Daylights               Timothy Dalton
The Man with the Golden Gun           Roger Moore
The Spy Who Loved Me                  Roger Moore
The World Is Not Enough            Pierce Brosnan
Thunderball                          Sean Connery
Tomorrow Never Dies                Pierce Brosnan
You Only Live Twice                  Sean Connery
Name: Actor, dtype: str

In [153]:
b

,Year,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,1985,John Glen,275.2,54.5,9.1
Casino Royale,2006,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Lewis Gilbert,514.2,59.9,4.4

In [154]:
b["Director"]

Film
A View to a Kill                            John Glen
Casino Royale                         Martin Campbell
Casino Royale                              Ken Hughes
Diamonds Are Forever                     Guy Hamilton
Die Another Day                          Lee Tamahori
Dr. No                                  Terence Young
For Your Eyes Only                          John Glen
From Russia with Love                   Terence Young
GoldenEye                             Martin Campbell
Goldfinger                               Guy Hamilton
Licence to Kill                             John Glen
Live and Let Die                         Guy Hamilton
Moonraker                               Lewis Gilbert
Never Say Never Again                  Irvin Kershner
Octopussy                                   John Glen
On Her Majesty's Secret Service         Peter R. Hunt
Quantum of Solace                        Marc Forster
Skyfall                                    Sam Mendes
Spectre                                    Sam Mendes
The Living Daylights                        John Glen
The Man with the Golden Gun              Guy Hamilton
The Spy Who Loved Me                    Lewis Gilbert
The World Is Not Enough                 Michael Apted
Thunderball                             Terence Young
Tomorrow Never Dies                Roger Spottiswoode
You Only Live Twice                     Lewis Gilbert
Name: Director, dtype: str

# Create random sample

In [160]:
b = pd.read_csv("jamesbond.csv", index_col= "Film")
b.sort_index(inplace=True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [156]:
b.sample()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3

In [157]:
b.sample(n=2)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [158]:
b.sample(frac = .23)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN

In [165]:
b.sample(n = 3, axis = 0) # axis = 0 se refiere a las filas

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [166]:
b.sample(n = 3, axis = 1)

                                 Budget  Box Office  Bond Actor Salary
Film
A View to a Kill                   54.5       275.2                9.1
Casino Royale                     145.3       581.5                3.3
Casino Royale                      85.0       315.0                NaN
Diamonds Are Forever               34.7       442.5                5.8
Die Another Day                   154.2       465.4               17.9
Dr. No                              7.0       448.8                0.6
For Your Eyes Only                 60.2       449.4                NaN
From Russia with Love              12.6       543.8                1.6
GoldenEye                          76.9       518.5                5.1
Goldfinger                         18.6       820.4                3.2
Licence to Kill                    56.7       250.9                7.9
Live and Let Die                   30.8       460.3                NaN
Moonraker                          91.5       535.0                NaN
Never Say Never Again              86.0       380.0                NaN
Octopussy                          53.9       373.8                7.8
On Her Majesty's Secret Service    37.3       291.5                0.6
Quantum of Solace                 181.4       514.2                8.1
Skyfall                           170.2       943.5               14.5
Spectre                           206.3       726.7                NaN
The Living Daylights               68.8       313.5                5.2
The Man with the Golden Gun        27.7       334.0                NaN
The Spy Who Loved Me               45.1       533.0                NaN
The World Is Not Enough           158.3       439.5               13.5
Thunderball                        41.9       848.1                4.7
Tomorrow Never Dies               133.9       463.2               10.0
You Only Live Twice                59.9       514.2                4.4

In [168]:
b.sample(n = 2, axis = 1) # Las columnas que se muestran son aleatorias

                                 Box Office           Actor
Film
A View to a Kill                      275.2     Roger Moore
Casino Royale                         581.5    Daniel Craig
Casino Royale                         315.0     David Niven
Diamonds Are Forever                  442.5    Sean Connery
Die Another Day                       465.4  Pierce Brosnan
Dr. No                                448.8    Sean Connery
For Your Eyes Only                    449.4     Roger Moore
From Russia with Love                 543.8    Sean Connery
GoldenEye                             518.5  Pierce Brosnan
Goldfinger                            820.4    Sean Connery
Licence to Kill                       250.9  Timothy Dalton
Live and Let Die                      460.3     Roger Moore
Moonraker                             535.0     Roger Moore
Never Say Never Again                 380.0    Sean Connery
Octopussy                             373.8     Roger Moore
On Her Majesty's Secret Service       291.5  George Lazenby
Quantum of Solace                     514.2    Daniel Craig
Skyfall                               943.5    Daniel Craig
Spectre                               726.7    Daniel Craig
The Living Daylights                  313.5  Timothy Dalton
The Man with the Golden Gun           334.0     Roger Moore
The Spy Who Loved Me                  533.0     Roger Moore
The World Is Not Enough               439.5  Pierce Brosnan
Thunderball                           848.1    Sean Connery
Tomorrow Never Dies                   463.2  Pierce Brosnan
You Only Live Twice                   514.2    Sean Connery

# The .nsmallest() and .largest() method

In [169]:
b = pd.read_csv("jamesbond.csv", index_col= "Film")
b.sort_index(inplace=True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [170]:
b.sort_values("Box Office", ascending = False).head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [171]:
b.nsmallest(n=2, columns="Box Office") # nsmallest sirve para mostrar las n filas con los valores más pequeños en la columna especificada

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1

In [ ]:
b.nlargest(3, columns="Box Office") # Muestra las 3 peliculas con mayor recaudacion

In [173]:
b.nlargest(3, columns="Budget") # Muestra las 3 peliculas con mayor recaudacion

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5

In [174]:
b.nsmallest(n=6, columns="Bond Actor Salary")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [175]:
b["Box Office"].nlargest(8)

Film
Skyfall                  943.5
Thunderball              848.1
Goldfinger               820.4
Spectre                  726.7
Casino Royale            581.5
From Russia with Love    543.8
Moonraker                535.0
The Spy Who Loved Me     533.0
Name: Box Office, dtype: float64

In [177]:
b["Year"].nsmallest(2)

Film
Dr. No                   1962
From Russia with Love    1963
Name: Year, dtype: int64

# Filterring with the where

In [178]:
b = pd.read_csv("jamesbond.csv", index_col= "Film")
b.sort_index(inplace=True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [179]:
mask = b["Actor"] == "Sean Connery"

In [181]:
b[mask] # Se usa para desplegar y filtrar en el data frame

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [183]:
b.where(mask) # Sirve para filtrar

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,1971.0,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,1962.0,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,1963.0,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,1983.0,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,NaN,NaN,NaN,NaN,NaN,NaN
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,1967.0,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [185]:
b.where(b["Box Office"] > 800)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,NaN,NaN,NaN,NaN,NaN,NaN
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,NaN,NaN,NaN,NaN,NaN,NaN
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,NaN,NaN,NaN,NaN,NaN,NaN
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,NaN,NaN,NaN,NaN,NaN,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,2012.0,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,NaN,NaN,NaN,NaN,NaN,NaN

In [186]:
b = pd.read_csv("jamesbond.csv", index_col= "Film")
b.sort_index(inplace=True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [187]:
b.columns

Index(['Year', 'Actor', 'Director', 'Box Office', 'Budget',
       'Bond Actor Salary'],
      dtype='str')

In [188]:
b.columns = [column_name.replace(" ","_") for column_name in b.columns]

In [189]:
b.columns

Index(['Year', 'Actor', 'Director', 'Box_Office', 'Budget',
       'Bond_Actor_Salary'],
      dtype='str')

In [192]:
b.query('Actor == "Sean Connery"')

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [194]:
b.query('Director == "Terence Young"')

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7

In [196]:
b.query("Actor != 'Roger Moore'")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [198]:
b.query("Actor != 'Roger Moore' and Director == 'John Glen'")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2

In [199]:
b.query("Actor in ['Timothy Dalton', 'George Lazenby']")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2

In [200]:
b.query("Actor not in ['Timothy Dalton', 'George Lazenby']")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

# A review of the .apply() method on single columns

In [218]:
b = pd.read_csv("jamesbond.csv", index_col= "Film")
b.sort_index(inplace=True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [202]:
# Tengo una columna y esa columna la voy a limpiar de caracteres raros y esa nueva columna la voy a almacenar

In [212]:
def convert_to_string_add_millions(number):
    return str(number) + " Millones"
b["Box Office"] = b["Box Office"].apply(convert_to_string_add_millions)

In [213]:
b

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2 Millones,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5 Millones,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0 Millones,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5 Millones,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4 Millones,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8 Millones,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4 Millones,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8 Millones,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5 Millones,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4 Millones,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9 Millones,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3 Millones,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0 Millones,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0 Millones,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8 Millones,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5 Millones,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2 Millones,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5 Millones,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7 Millones,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5 Millones,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0 Millones,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0 Millones,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5 Millones,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1 Millones,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2 Millones,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2 Millones,59.9,4.4

In [219]:
columns = ["Box Office", "Budget", "Bond Actor Salary"]
for col in columns:
    b[col] = b[col].apply(convert_to_string_add_millions)

In [220]:
b

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2 Millones,54.5 Millones,9.1 Millones
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5 Millones,145.3 Millones,3.3 Millones
Casino Royale,1967,David Niven,Ken Hughes,315.0 Millones,85.0 Millones,nan Millones
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5 Millones,34.7 Millones,5.8 Millones
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4 Millones,154.2 Millones,17.9 Millones
Dr. No,1962,Sean Connery,Terence Young,448.8 Millones,7.0 Millones,0.6 Millones
For Your Eyes Only,1981,Roger Moore,John Glen,449.4 Millones,60.2 Millones,nan Millones
From Russia with Love,1963,Sean Connery,Terence Young,543.8 Millones,12.6 Millones,1.6 Millones
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5 Millones,76.9 Millones,5.1 Millones
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4 Millones,18.6 Millones,3.2 Millones
Licence to Kill,1989,Timothy Dalton,John Glen,250.9 Millones,56.7 Millones,7.9 Millones
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3 Millones,30.8 Millones,nan Millones
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0 Millones,91.5 Millones,nan Millones
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0 Millones,86.0 Millones,nan Millones
Octopussy,1983,Roger Moore,John Glen,373.8 Millones,53.9 Millones,7.8 Millones
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5 Millones,37.3 Millones,0.6 Millones
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2 Millones,181.4 Millones,8.1 Millones
Skyfall,2012,Daniel Craig,Sam Mendes,943.5 Millones,170.2 Millones,14.5 Millones
Spectre,2015,Daniel Craig,Sam Mendes,726.7 Millones,206.3 Millones,nan Millones
The Living Daylights,1987,Timothy Dalton,John Glen,313.5 Millones,68.8 Millones,5.2 Millones
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0 Millones,27.7 Millones,nan Millones
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0 Millones,45.1 Millones,nan Millones
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5 Millones,158.3 Millones,13.5 Millones
Thunderball,1965,Sean Connery,Terence Young,848.1 Millones,41.9 Millones,4.7 Millones
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2 Millones,133.9 Millones,10.0 Millones
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2 Millones,59.9 Millones,4.4 Millones

In [1]:
import pandas as pd
b = pd.read_csv("jamesbond.csv", index_col= "Film")
b.sort_index(inplace=True)
b.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [14]:
def good_movie(row):
    actor = row["Actor"]
    budget = row["Budget"]

    if actor == "Pierce Brosnan":
        return "The Best"
    elif actor == "Roger Moore" and budget > 40:
        return "Enjoyable"
    else:
        return "I have no clue"
b.apply(good_movie, axis = 1)

Film
A View to a Kill                        Enjoyable
Casino Royale                      I have no clue
Casino Royale                      I have no clue
Diamonds Are Forever               I have no clue
Die Another Day                          The Best
Dr. No                             I have no clue
For Your Eyes Only                      Enjoyable
From Russia with Love              I have no clue
GoldenEye                                The Best
Goldfinger                         I have no clue
Licence to Kill                    I have no clue
Live and Let Die                   I have no clue
Moonraker                               Enjoyable
Never Say Never Again              I have no clue
Octopussy                               Enjoyable
On Her Majesty's Secret Service    I have no clue
Quantum of Solace                  I have no clue
Skyfall                            I have no clue
Spectre                            I have no clue
The Living Daylights               I have no clue
The Man with the Golden Gun        I have no clue
The Spy Who Loved Me                    Enjoyable
The World Is Not Enough                  The Best
Thunderball                        I have no clue
Tomorrow Never Dies                      The Best
You Only Live Twice                I have no clue
dtype: str