In [1]:
# Cargar el archivo y indexar por nombre y ordenar de forma permanente
import pandas as pd
df = pd.read_csv("employees.csv", index_col = "First Name", parse_dates = ["Start Date"])
df.sort_index(inplace = True)
df

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Aaron,Male,2012-02-17,10:20 AM,61602,11.849,True,Marketing
Aaron,Male,1994-01-29,6:48 PM,58755,5.097,True,Marketing
Aaron,Male,1990-07-22,2:53 PM,52119,11.343,True,Client Services
Aaron,NaN,1986-01-22,7:39 PM,63126,18.424,False,Client Services
Adam,Male,2011-05-21,1:45 AM,95327,15.120,False,Distribution
...,...,...,...,...,...,...,...
NaN,Male,2001-05-23,7:52 PM,103877,6.322,NaN,Distribution
NaN,Female,2000-08-23,4:19 PM,95866,19.388,NaN,Sales
NaN,Female,1985-09-15,1:50 AM,133472,16.941,NaN,Distribution
NaN,Male,2012-07-30,3:07 PM,107351,5.329,NaN,Marketing
NaN,Female,2010-09-14,5:19 AM,143638,9.662,NaN,NaN

In [2]:
# Genera un reporte con filtros que contenga los registros de los empleados masculinos y de marketing
mask1 = df["Gender"] == "Male"
mask2 = df["Team"] == "Marketing"

df[mask1 & mask2]

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Aaron,Male,2012-02-17,10:20 AM,61602,11.849,True,Marketing
Aaron,Male,1994-01-29,6:48 PM,58755,5.097,True,Marketing
Arthur,Male,2014-12-16,4:56 PM,66819,6.639,True,Marketing
Benjamin,Male,1984-09-11,6:37 AM,84810,15.794,False,Marketing
Charles,Male,2004-09-14,8:13 PM,107391,1.260,True,Marketing
Craig,Male,2000-02-27,7:45 AM,37598,7.757,True,Marketing
Craig,Male,1984-02-08,4:45 AM,113506,19.642,False,Marketing
Douglas,Male,1993-08-06,12:42 PM,97308,6.945,True,Marketing
Earl,Male,2013-06-15,3:00 AM,48046,7.737,False,Marketing
Ernest,Male,1990-01-28,12:08 AM,81919,15.118,False,Marketing
George,Male,2013-06-21,5:47 PM,98874,4.479,True,Marketing
Gregory,Male,1984-06-18,3:46 AM,82726,16.304,True,Marketing
Howard,Male,1982-10-05,7:22 AM,97490,5.460,True,Marketing
Jeremy,Male,2001-08-09,3:56 AM,43354,13.946,False,Marketing
Jesse,Male,1999-10-25,3:35 PM,118733,9.653,False,Marketing
Joe,Male,2000-04-14,3:14 PM,50645,11.119,False,Marketing
John,Male,1989-12-23,7:01 AM,80740,19.305,False,Marketing
Johnny,Male,1992-09-14,8:21 AM,115194,5.861,True,Marketing
Johnny,Male,2016-02-26,7:39 PM,76394,5.437,True,Marketing
Jonathan,Male,1995-04-06,10:38 PM,56993,18.623,False,Marketing
Joshua,Male,1997-06-27,3:23 PM,95003,5.197,True,Marketing
Lawrence,Male,2005-05-13,1:25 AM,74640,18.641,False,Marketing
Lawrence,Male,1984-10-01,2:06 PM,102589,17.952,True,Marketing
Matthew,Male,2013-07-31,8:04 AM,142373,2.462,False,Marketing
Matthew,Male,1995-09-05,2:12 AM,100612,13.645,False,Marketing
Paul,Male,2008-06-03,3:05 PM,41054,12.299,False,Marketing
Phillip,Male,1984-10-07,11:05 AM,36837,14.660,False,Marketing
Ralph,Male,2004-11-11,1:35 AM,71896,4.232,True,Marketing
Roger,Male,2004-11-19,3:55 PM,51430,6.460,False,Marketing
Roger,Male,2010-07-03,5:11 PM,105689,13.320,True,Marketing
Roger,Male,2015-08-03,4:56 PM,125033,4.887,True,Marketing
Samuel,Male,2012-05-25,4:40 PM,85550,11.593,True,Marketing
Scott,Male,2012-11-17,2:47 PM,146812,1.965,True,Marketing
Sean,Male,1996-05-04,8:59 PM,135490,19.934,False,Marketing
Thomas,Male,1995-06-04,2:24 PM,62096,17.029,False,Marketing
Walter,Male,1992-05-21,12:39 AM,144701,16.323,True,Marketing
Willie,Male,2003-11-27,6:21 AM,64363,4.023,False,Marketing
Willie,Male,2006-06-06,9:45 AM,55281,4.935,True,Marketing
NaN,Male,1997-04-22,9:36 PM,65078,3.095,NaN,Marketing
NaN,Male,1995-02-21,12:26 AM,136602,10.429,NaN,Marketing
NaN,Male,2012-07-30,3:07 PM,107351,5.329,NaN,Marketing

In [3]:
# Filtrar los empleados que son parte del Senior Managment o que empezaron antes de 1990
mask1 = df["Senior Management"] == True
mask2 = df["Start Date"] < "01-01-1990"

df[mask1 | mask2]

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Aaron,Male,2012-02-17,10:20 AM,61602,11.849,True,Marketing
Aaron,Male,1994-01-29,6:48 PM,58755,5.097,True,Marketing
Aaron,Male,1990-07-22,2:53 PM,52119,11.343,True,Client Services
Aaron,NaN,1986-01-22,7:39 PM,63126,18.424,False,Client Services
Adam,Male,1990-12-24,8:57 PM,110194,14.727,True,Product
...,...,...,...,...,...,...,...
NaN,Female,1982-07-24,12:00 AM,57811,8.941,NaN,Marketing
NaN,Female,1980-12-27,2:27 AM,80399,12.254,NaN,Distribution
NaN,NaN,1988-08-01,1:35 AM,87103,5.665,NaN,NaN
NaN,Male,1980-09-05,7:36 AM,114896,13.823,NaN,Client Services
NaN,Female,1985-09-15,1:50 AM,133472,16.941,NaN,Distribution

In [4]:
# Filtra los empleados que se llaman Robert que son parte del Client Services o que empezaron despues de junio de 2016

mask1 = df.index == "Robert"
mask2 = df["Team"] == "Client Services"
mask3 = df["Start Date"] > "30-06-2016"

df[mask1 & (mask2 | mask3)]

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Robert,Male,1994-10-29,4:26 AM,123294,19.894,False,Client Services

In [5]:
# Filtra los empleados que son parte del Legal, Sales o Product

mask1 = df["Team"] == "Legal" 
mask2 = df["Team"] == "Sales"
mask3 = df["Team"] == "Product"

df[mask1 | mask2 | mask3]

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Adam,Male,1990-12-24,8:57 PM,110194,14.727,True,Product
Alan,Male,2012-02-17,12:26 AM,41453,10.084,False,Product
Albert,Male,2012-05-15,6:24 PM,129949,10.169,True,Sales
Alice,Female,1988-09-03,8:54 PM,63571,15.397,True,Product
Alice,Female,1995-10-16,9:19 PM,92799,2.782,False,Sales
...,...,...,...,...,...,...,...
NaN,Female,2008-07-08,11:40 PM,62960,14.356,NaN,Sales
NaN,Male,1983-10-13,11:59 PM,139754,12.740,NaN,Sales
NaN,NaN,1991-04-15,3:39 AM,132505,13.592,NaN,Product
NaN,Male,1994-12-13,10:34 AM,141311,5.478,NaN,Product
NaN,Female,2000-08-23,4:19 PM,95866,19.388,NaN,Sales

In [6]:
mask = df["Team"].isin(["Legal", "Sales", "Product"])
df[mask]

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Adam,Male,1990-12-24,8:57 PM,110194,14.727,True,Product
Alan,Male,2012-02-17,12:26 AM,41453,10.084,False,Product
Albert,Male,2012-05-15,6:24 PM,129949,10.169,True,Sales
Alice,Female,1988-09-03,8:54 PM,63571,15.397,True,Product
Alice,Female,1995-10-16,9:19 PM,92799,2.782,False,Sales
...,...,...,...,...,...,...,...
NaN,Female,2008-07-08,11:40 PM,62960,14.356,NaN,Sales
NaN,Male,1983-10-13,11:59 PM,139754,12.740,NaN,Sales
NaN,NaN,1991-04-15,3:39 AM,132505,13.592,NaN,Product
NaN,Male,1994-12-13,10:34 AM,141311,5.478,NaN,Product
NaN,Female,2000-08-23,4:19 PM,95866,19.388,NaN,Sales

In [7]:
mask1 = (df["Team"] == "Legal") | (df["Team"] == "Sales") | (df["Team"] == "Product")

df[mask1]

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Adam,Male,1990-12-24,8:57 PM,110194,14.727,True,Product
Alan,Male,2012-02-17,12:26 AM,41453,10.084,False,Product
Albert,Male,2012-05-15,6:24 PM,129949,10.169,True,Sales
Alice,Female,1988-09-03,8:54 PM,63571,15.397,True,Product
Alice,Female,1995-10-16,9:19 PM,92799,2.782,False,Sales
...,...,...,...,...,...,...,...
NaN,Female,2008-07-08,11:40 PM,62960,14.356,NaN,Sales
NaN,Male,1983-10-13,11:59 PM,139754,12.740,NaN,Sales
NaN,NaN,1991-04-15,3:39 AM,132505,13.592,NaN,Product
NaN,Male,1994-12-13,10:34 AM,141311,5.478,NaN,Product
NaN,Female,2000-08-23,4:19 PM,95866,19.388,NaN,Sales

In [8]:
# Filtra los empleados que no tienen un  equipo asignado (Team es null)

df["Team"].isnull()

First Name
Aaron    False
Aaron    False
Aaron    False
Aaron    False
Adam     False
         ...
NaN      False
NaN      False
NaN      False
NaN      False
NaN       True
Name: Team, Length: 1000, dtype: bool

In [9]:
# Crea un reporte que contenga los empleados que ganan entre 60000 y 70000 dolares
mask = df["Salary"].between(60000, 70000)

df[mask]

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Aaron,Male,2012-02-17,10:20 AM,61602,11.849,True,Marketing
Aaron,NaN,1986-01-22,7:39 PM,63126,18.424,False,Client Services
Albert,Male,1997-02-01,4:20 PM,67827,19.717,True,Engineering
Alice,Female,1988-09-03,8:54 PM,63571,15.397,True,Product
Amy,NaN,1984-12-25,10:52 AM,63888,18.115,True,Product
...,...,...,...,...,...,...,...
Willie,Male,2003-11-27,6:21 AM,64363,4.023,False,Marketing
NaN,Female,2008-07-08,11:40 PM,62960,14.356,NaN,Sales
NaN,Male,2011-10-09,9:29 AM,69906,4.844,NaN,Engineering
NaN,Male,1997-04-22,9:36 PM,65078,3.095,NaN,Marketing
NaN,Male,1995-04-07,4:32 AM,60411,12.048,NaN,Human Resources

In [10]:
# Nomina de todos los empleados de marketing 

mask = df["Team"] == "Marketing"
nomina = df.loc[mask, "Salary"].sum()

print(f"El total de la nomina es: ${nomina} dólares")

El total de la nomina es: $8862688 dólares

In [11]:
# Todos los empleados que empezaron a trabajar entre el 1 de enero de 1991 y el 1 de enero de 1992

mask = df["Start Date"].between("01-01-1991", "01-01-1992")

df[mask]

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Amanda,NaN,1991-08-11,2:15 PM,46665,19.391,True,Client Services
Barbara,Female,1991-09-02,3:41 PM,127297,11.905,True,Product
Bonnie,Female,1991-07-02,1:27 AM,104897,5.118,True,Human Resources
Brenda,NaN,1991-05-29,6:32 AM,82439,19.062,False,Sales
Carl,NaN,1991-10-26,8:11 AM,100888,12.490,True,Business Development
Cynthia,Female,1991-09-14,1:08 PM,51633,13.472,True,Business Development
Donald,Male,1991-08-01,2:25 AM,61999,6.466,False,Product
Donna,Female,1991-11-27,1:59 PM,64088,6.155,True,Legal
Irene,NaN,1991-02-28,10:23 PM,135369,4.380,False,Business Development
Janice,NaN,1991-11-19,6:02 PM,139791,16.968,False,Business Development
Jeremy,Male,1991-05-19,1:40 PM,131513,1.876,True,Finance
Judy,Female,1991-07-01,2:33 AM,109510,13.457,True,Legal
Justin,NaN,1991-02-10,4:58 PM,38344,3.794,False,Legal
Justin,Male,1991-07-25,12:45 AM,112975,9.699,False,Human Resources
Michael,Male,1991-11-22,12:57 PM,98753,16.443,True,Human Resources
Patrick,NaN,1991-07-14,2:24 AM,124488,14.837,True,Sales
Peter,Male,1991-05-22,1:39 AM,102577,12.026,True,Product
Samuel,Male,1991-12-19,2:54 AM,76076,5.319,True,Finance
Sara,Female,1991-09-23,6:17 PM,97058,9.402,False,Finance
Scott,NaN,1991-07-11,6:58 PM,122367,5.218,False,Legal
Thomas,Male,1991-09-07,9:51 AM,65251,11.211,False,Distribution
Timothy,Male,1991-08-25,10:37 AM,92587,8.475,False,Finance
Victor,Male,1991-04-11,7:44 AM,70817,17.138,False,Engineering
NaN,Male,1991-06-22,8:58 PM,76189,18.988,NaN,Legal
NaN,Female,1991-07-09,6:52 PM,42341,7.014,NaN,Sales
NaN,Female,1991-06-17,12:49 PM,71945,5.560,NaN,Marketing
NaN,NaN,1991-04-15,3:39 AM,132505,13.592,NaN,Product

In [12]:
# Cuántos empleado unicos hay en el dataframe

df.index.is_unique

df.index.nunique()

200

In [18]:
# Cuantos equipos son los equipos (Team) unicos en el dataframe
num_equipos = df['Team'].nunique()
print(num_equipos)

10

In [25]:
# Cuantos empleados únicos hay en el dataframe que no tienen un equipo asignado
empleados_sin_equipo = df[df["Team"].isnull()]
cantidad_unicos = empleados_sin_equipo.index.nunique()
print(cantidad_unicos)

33